# Generated by Django 2.0.5 on 2018-05-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='diff',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
